### ISSUE TITLE
AIKA #1 - Setup, SDL, SDL_gpu

### ISSUE THREAD

**Issue by SSYGEN** [SSYGEN/blog#34]
I'm starting a new tutorial series on writing an engine for 2D games in C using SDL. I'm writing my articles [on my own site now](http://ssygen.com) but I'll still use this repository for comments. So this issue is for comments on this article:

# [AIKA #1 - Setup, SDL, SDL_gpu](http://ssygen.com/posts/aika-1)

**Comment by flamendless** [comment]
Awesome! What do you use for your  Site?

**Comment by SSYGEN** [comment]
I built it from scratch

**Comment by flamendless** [comment]
@SSYGEN really? With lua? What libraries?

**Comment by SSYGEN** [comment]
@flamendless The site is here https://github.com/SSYGEN/SSYGEN

**Comment by dbriemann** [comment]
@SSYGEN First of all I really like to read your blog. Cannot wait to read more about your custom framework/engine.

Second of all your way of blogging somehow inspired me and today I released my static site/blog generator based on Github issues and pages. If you are interested check out

1. the repo: https://github.com/dbriemann/glyph-zero 
2. how it looks like after building from issues: https://dbriemann.github.io/blog/2-introducing-glyph-static-site-generator-powered-by-github-issues-and-pages.html

Since you rolled your own solution already you probably won't need it but I thought you might be interested.
